dist: trusty
language: c
compiler:
  - gcc
  - clang
before_install:
  - sudo pip install codecov
install:
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq libjansson-dev check libssl-dev lcov
script:
  - autoreconf -i && ./configure --enable-code-coverage && make check-code-coverage
after_success:
  - codecov
